apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: finals-backend
  name: finals-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: finals-backend
    spec:
      containers:
      - name: finals-backend
        image: sighup/kubeprimer_backend:0.1
        ports:
        - containerPort: 4466
      restartPolicy: Always
