apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: finals-backend-service
  name: svc-backend
spec:
  ports:
  - port: 4466
    targetPort: 4466
  selector:
    app: finals-backend
