apiVersion: v1
kind: Service
metadata:
  labels:
    service: finals-frontend-service
  name: finals-frontend-service
spec:
  type: NodePort
  ports:
  - name: "web"
    port: 4455
    protocol: TCP
  selector:
    app: finals-frontend
