apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  activeDeadlineSeconds: 100
  # completions: 10
  # parallelism: 3
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: alpine
        command: ["sleep",  "10"]
      restartPolicy: Never # Only Never or OnFailure is allowed
